<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="11.1.0" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="9.0.2" />
    <PackageReference Include="Microsoft.ML.OnnxRuntime" Version="1.20.1" />
    <PackageReference Include="Microsoft.ML.OnnxRuntime.DirectML" Version="1.20.1" />
    <PackageReference Include="NAudio" Version="2.2.1" />
    <PackageReference Include="NAudio.Core" Version="2.2.1" />
    <PackageReference Include="NAudio.Wasapi" Version="2.2.1" />
    <PackageReference Include="SharpCompress" Version="0.39.0" />
    <PackageReference Include="System.Speech" Version="8.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Nexi.Data.Models\Nexi.Data.Models.csproj" />
    <ProjectReference Include="..\Nexi.Data\Nexi.Data.csproj" />
  </ItemGroup>
  
</Project>
